import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState } from 'react';
import { useRouter } from 'next/router';
import Question from '../public/que.svg';
import ReactTooltip from 'react-tooltip';

export default function Home() {

  const apiUrl = "https://registerbackend.opendatabayern.de/api/";
    //const apiUrl = "http://localhost:3100/api/";

    const [query, setQuery] = useState({
        email:"",
        userName:"",
        password:"",
        confirmPass:""
    }); 
 
    
    const [change, setChange] = useState(false);
    const [valid, setValid] = useState(false);
    const handleChange = () => (e) => {
      const name = e.target.name;
      const value = e.target.value;
      setQuery((prevState) => ({
          ...prevState,
          [name]: value
      }));
      setChange(true);
      if(query.password!=null && query.password==query.confirmPass)
         setValid(true)
      else
         setValid(false)
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div className="container center-container">
          <div className="register-form-container">
            <div className="reg-details">
            <h2>Registrierung abschließen</h2>
            <br/>
            <h4>
            Ihr Username lautet {query.userName}
            </h4>
            <br/>
           <h4>
               Bitte setzen sie ein neues Passwort fest
           </h4>
            </div>
            <form method="post" className="dataset-form login-form">
              <div class="form-group control-medium">
                <label class="control-label" for="field-login">
                Password
                </label>
                <div class="controls ">
                  <input
                    id="field-login"
                    type="password"
                    name="password"
                    value={query.password}
                    placeholder="************"
                    class="form-control"
                    onChange={handleChange()} 
                  />
                 
                </div>
              </div>

              <div class="form-group control-medium">
                <label class="control-label" for="field-login">
                Confirm Password
                </label>
                <div class="controls ">
                  <input
                    id="field-login"
                    type="password"
                    name="confirmPass"
                    placeholder="************"
                    value={query.confirmPass}
                    class="form-control"
                    onChange={handleChange()} 
                  />
                </div>
              </div>
              
              <button class={!valid?"blue-btn inactive-btn":"blue-btn active-btn"}  disabled={valid?false:true}>Passwort erstellen</button>
            </form>
          </div>
        </div>
      </main>
    </div>
  );
}
